"""Opening Research sub-graph — 3-step LLM pipeline for opening reports."""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from typing import Any

from src.agents.graphs._shared import _read_optional_str, _read_payload_params
from src.agents.workspace_lead_agent import register_feature_graph
from src.models.router import route_writing_model
from src.task.progress import emit_runtime_update, get_runtime_state
from src.task.runtime_blocks import (
    advance_runtime_phase,
    append_runtime_activity,
    runtime_progress_for_phase,
    upsert_runtime_block,
)

logger = logging.getLogger(__name__)


async def _emit_bound_runtime(
    *,
    message: str,
    current_phase: str,
    stage_transition: bool = False,
) -> None:
    runtime = get_runtime_state()
    if runtime is None:
        return
    await emit_runtime_update(
        progress_value=max(runtime_progress_for_phase(runtime), 5),
        message=message,
        current_phase=current_phase,
        runtime=runtime,
        stage_transition=stage_transition,
    )


def _resolve_writing_model(requested_model: str | None) -> str:
    """Resolve a writing model with safe fallback."""
    try:
        return route_writing_model(requested_model=requested_model)
    except Exception:
        return requested_model or "default"

# ---------------------------------------------------------------------------
# Report type constants
# ---------------------------------------------------------------------------
_REPORT_TYPES = {"opening_report", "literature_review", "feasibility_analysis"}


# ---------------------------------------------------------------------------
# Main graph entry point
# ---------------------------------------------------------------------------
@register_feature_graph("opening_research", workspace_type="thesis")
async def opening_research_graph(
    initial_state: dict[str, Any],
    payload: dict[str, Any],
) -> dict[str, Any]:
    """Execute 3-step opening research pipeline.

    Pipeline:
        1. analyze_research_status — Analyze research landscape
        2. plan_methodology — Plan research methodology
        3. generate_report_sections — Generate report sections

    Output is generated by LLM pipeline and combined into artifact payload.
    """
    workspace_id = str(payload.get("workspace_id", ""))
    params = _read_payload_params(payload)
    topic = str(params.get("topic") or payload.get("workspace_name") or "未命名研究主题").strip()
    if not topic:
        topic = "未命名研究主题"
    report_type = _normalize_report_type(str(params.get("report_type") or "opening_report"))
    workspace_description = str(payload.get("workspace_description", ""))
    memory_context = initial_state.get("memory_context")
    requested_model = _read_optional_str(params.get("model_id"))
    model_id = _resolve_writing_model(requested_model)
    runtime = get_runtime_state()

    # Step 0: Load literature
    literature = await _load_literature(workspace_id)
    literature_highlights = _build_literature_highlights(literature)
    if runtime is not None:
        upsert_runtime_block(
            runtime,
            {
                "id": "literature",
                "kind": "metrics",
                "title": "文献基础",
                "entries": [
                    {"label": "主题", "value": topic},
                    {"label": "报告类型", "value": report_type},
                    {"label": "文献数量", "value": str(len(literature))},
                ],
            },
        )
        if literature_highlights:
            upsert_runtime_block(
                runtime,
                {
                    "id": "literature-highlights",
                    "kind": "list",
                    "title": "文献线索",
                    "items": [
                        {"title": item, "description": ""}
                        for item in literature_highlights[:6]
                    ],
                },
            )
        append_runtime_activity(
            runtime,
            title="文献背景已加载",
            description=f"已载入 {len(literature)} 条文献，开始分析研究现状。",
            tone="info",
        )
        await _emit_bound_runtime(
            message="正在分析研究现状与问题空间...",
            current_phase="research_status",
            stage_transition=True,
        )

    # Step 1: Analyze research status
    research_analysis = await _analyze_research_status(
        literature=literature,
        focus_topic=topic,
        memory_context=memory_context,
        model_id=model_id,
    )
    if research_analysis is None:
        raise RuntimeError("opening_research_failed: research_status_generation_failed")
    if runtime is not None:
        upsert_runtime_block(
            runtime,
            {
                "id": "research-analysis",
                "kind": "text",
                "title": "研究现状分析",
                "content": json.dumps(research_analysis, ensure_ascii=False, indent=2)
                if research_analysis is not None
                else "未返回结构化研究现状分析。",
            },
        )
        append_runtime_activity(
            runtime,
            title="研究现状分析完成",
            description="已完成研究背景分析，进入方法规划阶段。",
            tone="success" if research_analysis is not None else "warning",
        )
        advance_runtime_phase(runtime, "research_status", "methodology")
        await _emit_bound_runtime(
            message="正在规划报告的方法路线与结构...",
            current_phase="methodology",
            stage_transition=True,
        )

    # Step 2: Plan methodology
    methodology_plan = await _plan_methodology(
        research_analysis=research_analysis,
        report_type=report_type,
        topic=topic,
        model_id=model_id,
    )
    if methodology_plan is None:
        raise RuntimeError("opening_research_failed: methodology_planning_failed")
    if runtime is not None:
        upsert_runtime_block(
            runtime,
            {
                "id": "methodology-plan",
                "kind": "text",
                "title": "方法规划",
                "content": json.dumps(methodology_plan, ensure_ascii=False, indent=2)
                if methodology_plan is not None
                else "未返回结构化方法规划。",
            },
        )
        append_runtime_activity(
            runtime,
            title="方法规划完成",
            description="已形成方法路线，开始生成报告章节。",
            tone="success" if methodology_plan is not None else "warning",
        )
        advance_runtime_phase(runtime, "methodology", "report")
        await _emit_bound_runtime(
            message="正在整合章节并生成报告...",
            current_phase="report",
            stage_transition=True,
        )

    # Step 3: Generate report sections
    sections = await _generate_report_sections(
        research_analysis=research_analysis,
        methodology_plan=methodology_plan,
        report_type=report_type,
        topic=topic,
        workspace_description=workspace_description,
        literature_highlights=literature_highlights,
        memory_context=memory_context,
        model_id=model_id,
    )
    if sections is None:
        raise RuntimeError("opening_research_failed: section_generation_failed")
    if runtime is not None:
        upsert_runtime_block(
            runtime,
            {
                "id": "report-sections",
                "kind": "list",
                "title": "报告章节",
                "description": "已生成的章节摘要",
                "items": [
                    {
                        "title": str(section.get("title") or "未命名章节"),
                        "description": str(section.get("content") or "")[:220],
                        "meta": str(section.get("source") or ""),
                    }
                    for section in sections[:6]
                    if isinstance(section, dict)
                ],
            },
        )
        append_runtime_activity(
            runtime,
            title="报告章节已生成",
            description=f"已输出 {len(sections)} 个章节。",
            tone="success",
        )

    step_results = {
        "status_analysis": True,
        "methodology_planning": True,
        "section_generation": True,
    }

    return {
        "topic": topic,
        "report_type": report_type,
        "sections": sections,
        "research_analysis": research_analysis,
        "methodology_plan": methodology_plan,
        "reference_clues": literature_highlights,
        "literature_count": len(literature),
        "model_id": model_id,
        "generation_mode": "llm",
        "pipeline_steps": step_results,
        "generated_at": datetime.now(tz=UTC).isoformat(),
    }


# ---------------------------------------------------------------------------
# Helper: normalize report type
# ---------------------------------------------------------------------------
def _normalize_report_type(report_type: str) -> str:
    normalized = (report_type or "").strip().lower()
    if normalized not in _REPORT_TYPES:
        return "opening_report"
    return normalized


# ---------------------------------------------------------------------------
# Helper: load literature from DB
# ---------------------------------------------------------------------------
async def _load_literature(workspace_id: str) -> list[dict[str, Any]]:
    """Load workspace literature from DB."""
    from src.database import get_db_session
    from src.services.literature_service import LiteratureService

    try:
        async with get_db_session() as db:
            service = LiteratureService(db)
            response = await service.list_literature(workspace_id, offset=0, limit=120)
        items = response.get("items")
        return items if isinstance(items, list) else []
    except Exception:
        logger.exception("Failed to load literature for opening research")
        return []


# ---------------------------------------------------------------------------
# Helper: build literature highlights
# ---------------------------------------------------------------------------
def _build_literature_highlights(literature: list[dict[str, Any]], max_items: int = 8) -> list[str]:
    """Extract title(year) - venue strings for reference clues."""
    highlights: list[str] = []
    for item in literature[:max_items]:
        title = str(item.get("title") or "").strip()
        if not title:
            continue
        year = item.get("year")
        venue = str(item.get("venue") or "").strip()
        year_part = f"({year})" if year else ""
        venue_part = f" - {venue}" if venue else ""
        highlights.append(f"{title}{year_part}{venue_part}")
    return highlights


# ---------------------------------------------------------------------------
# Helper: parse JSON from LLM response
# ---------------------------------------------------------------------------
def _parse_json_response(text: str) -> dict[str, Any] | None:
    """Parse JSON from LLM response, handling markdown fences."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    try:
        parsed = json.loads(text)
        return parsed if isinstance(parsed, dict) else None
    except json.JSONDecodeError:
        return None


def _parse_json_list_response(text: str) -> list[dict[str, Any]] | None:
    """Parse JSON list from LLM response, handling markdown fences."""
    text = text.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    try:
        parsed = json.loads(text)
        if isinstance(parsed, list) and all(isinstance(item, dict) for item in parsed):
            return parsed
        return None
    except json.JSONDecodeError:
        return None


# ---------------------------------------------------------------------------
# Helper: build literature summary text for LLM prompts
# ---------------------------------------------------------------------------
def _build_literature_summary(literature: list[dict[str, Any]], max_items: int = 30) -> str:
    """Build a text summary of literature for use in LLM prompts."""
    summaries: list[str] = []
    for p in literature[:max_items]:
        title = p.get("title", "Unknown")
        year = p.get("year", "")
        citations = p.get("citations", 0)
        abstract = (p.get("abstract") or "")[:200]
        summaries.append(f"- {title} ({year}, cited {citations}x): {abstract}")
    return "\n".join(summaries) if summaries else "（暂无文献）"


# ---------------------------------------------------------------------------
# LLM Step 1: Analyze research status
# ---------------------------------------------------------------------------
_STEP1_PROMPT = """你是学术研究分析专家。基于以下文献列表和研究方向，分析当前研究现状。

研究方向: {topic}

文献列表:
{literature_summary}
{memory_context}

请分析并返回 JSON:
{{
  "research_status": "对该领域当前研究状态的概述（3-5句话）",
  "key_trends": ["趋势1", "趋势2", "趋势3"],
  "research_gaps": ["研究空白1", "研究空白2"],
  "theoretical_foundations": ["理论基础1", "理论基础2"]
}}

仅返回 JSON。"""


async def _analyze_research_status(
    literature: list[dict[str, Any]],
    focus_topic: str,
    memory_context: str | None,
    *,
    model_id: str = "default",
) -> dict[str, Any] | None:
    """Step 1: LLM analyzes research landscape. Returns None on failure."""
    try:
        from src.models.factory import create_chat_model

        model = create_chat_model(model_id, temperature=0.3)
    except Exception:
        return None

    lit_text = _build_literature_summary(literature)
    mem_text = f"\n用户记忆上下文:\n{memory_context}" if memory_context else ""

    prompt = _STEP1_PROMPT.format(
        topic=focus_topic,
        literature_summary=lit_text,
        memory_context=mem_text,
    )

    try:
        response = await model.ainvoke(prompt)
        content = response.content if hasattr(response, "content") else str(response)
        return _parse_json_response(content)
    except Exception:
        logger.exception("Step 1 (analyze_research_status) failed")
        return None


# ---------------------------------------------------------------------------
# LLM Step 2: Plan methodology
# ---------------------------------------------------------------------------
_STEP2_PROMPT = """你是学术方法论规划专家。基于前一步的研究现状分析，为以下报告类型规划研究方法。

报告类型: {report_type}
研究方向: {topic}

研究现状分析:
{research_analysis}

请规划并返回 JSON:
{{
  "objectives": ["研究目标1", "研究目标2", "研究目标3"],
  "methodology": "研究方法论概述（3-5句话）",
  "technical_approach": "技术路线概述（3-5句话）",
  "innovation_points": ["创新点1", "创新点2"]
}}

仅返回 JSON。"""


async def _plan_methodology(
    research_analysis: dict[str, Any] | None,
    report_type: str,
    topic: str,
    *,
    model_id: str = "default",
) -> dict[str, Any] | None:
    """Step 2: LLM plans research methodology. Returns None on failure."""
    try:
        from src.models.factory import create_chat_model

        model = create_chat_model(model_id, temperature=0.3)
    except Exception:
        return None

    analysis_text = json.dumps(research_analysis, ensure_ascii=False, indent=2) if research_analysis else "（前一步分析未生成，请基于通用学术方法论进行规划）"

    prompt = _STEP2_PROMPT.format(
        report_type=report_type,
        topic=topic,
        research_analysis=analysis_text,
    )

    try:
        response = await model.ainvoke(prompt)
        content = response.content if hasattr(response, "content") else str(response)
        return _parse_json_response(content)
    except Exception:
        logger.exception("Step 2 (plan_methodology) failed")
        return None


# ---------------------------------------------------------------------------
# LLM Step 3: Generate report sections
# ---------------------------------------------------------------------------
_STEP3_PROMPT = """你是学术报告撰写专家。基于研究分析和方法论规划，生成完整的报告章节。

报告类型: {report_type}
研究方向: {topic}

研究现状分析:
{research_analysis}

方法论规划:
{methodology_plan}

参考文献线索:
{literature_highlights}
{memory_context}

请按照以下结构生成报告章节，返回 JSON 列表:
{section_schema}

每个章节格式: {{"title": "章节标题", "content": "章节详细内容（200-500字）"}}

仅返回 JSON 列表。"""

_SECTION_SCHEMAS: dict[str, str] = {
    "opening_report": """[
  {{"title": "研究背景与意义", "content": "..."}},
  {{"title": "国内外研究现状", "content": "..."}},
  {{"title": "研究目标与主要内容", "content": "..."}},
  {{"title": "技术路线与方法设计", "content": "..."}},
  {{"title": "创新点与预期成果", "content": "..."}},
  {{"title": "进度安排与风险预案", "content": "..."}}
]""",
    "literature_review": """[
  {{"title": "检索范围与方法", "content": "..."}},
  {{"title": "代表性研究脉络", "content": "..."}},
  {{"title": "关键文献评述", "content": "..."}},
  {{"title": "研究空白与切入点", "content": "..."}}
]""",
    "feasibility_analysis": """[
  {{"title": "研究目标与约束条件", "content": "..."}},
  {{"title": "技术可行性", "content": "..."}},
  {{"title": "资源与数据可行性", "content": "..."}},
  {{"title": "计划与风险控制", "content": "..."}}
]""",
}


async def _generate_report_sections(
    research_analysis: dict[str, Any] | None,
    methodology_plan: dict[str, Any] | None,
    report_type: str,
    topic: str,
    workspace_description: str,
    literature_highlights: list[str],
    memory_context: str | None,
    *,
    model_id: str = "default",
) -> list[dict[str, Any]] | None:
    """Step 3: LLM generates full report sections."""
    try:
        from src.models.factory import create_chat_model

        model = create_chat_model(model_id, temperature=0.3)
    except Exception:
        return None

    analysis_text = (
        json.dumps(research_analysis, ensure_ascii=False, indent=2)
        if research_analysis
        else "（未生成）"
    )
    methodology_text = (
        json.dumps(methodology_plan, ensure_ascii=False, indent=2)
        if methodology_plan
        else "（未生成）"
    )
    lit_text = "\n".join(f"- {h}" for h in literature_highlights) if literature_highlights else "（暂无）"
    mem_text = f"\n用户记忆上下文:\n{memory_context}" if memory_context else ""
    section_schema = _SECTION_SCHEMAS.get(report_type, _SECTION_SCHEMAS["opening_report"])

    prompt = _STEP3_PROMPT.format(
        report_type=report_type,
        topic=topic,
        research_analysis=analysis_text,
        methodology_plan=methodology_text,
        literature_highlights=lit_text,
        memory_context=mem_text,
        section_schema=section_schema,
    )

    try:
        response = await model.ainvoke(prompt)
        content = response.content if hasattr(response, "content") else str(response)
        parsed = _parse_json_list_response(content)
        if parsed and len(parsed) >= 2:
            return [
                {"title": s.get("title", ""), "content": s.get("content", ""), "source": "llm"}
                for s in parsed
            ]
    except Exception:
        logger.exception("Step 3 (generate_report_sections) failed")

    return None
