"""Canonical artifact type taxonomy shared across layers."""

from enum import StrEnum


class ArtifactType(StrEnum):
    """Canonical artifact types used by persistence, validation, and features."""

    DEEP_RESEARCH_REPORT = "deep_research_report"
    RESEARCH_IDEA = "research_idea"
    RESEARCH_IDEAS = "research_ideas"
    METHODOLOGY = "methodology"
    FRAMEWORK_OUTLINE = "framework_outline"
    ABSTRACT = "abstract"
    INTRODUCTION = "introduction"
    LITERATURE_REVIEW = "literature_review"
    HYPOTHESIS = "hypothesis"
    RESULTS_ANALYSIS = "results_analysis"
    CONCLUSION = "conclusion"
    REFERENCES = "references"
    FIGURE = "figure"
    TABLE = "table"
    CODE_SNIPPET = "code_snippet"
    NOTE = "note"
    SUMMARY = "summary"
    OTHER = "other"
    METHODOLOGY_SECTION = "methodology_section"
    EXPERIMENT_SECTION = "experiment_section"
    RESULTS_SECTION = "results_section"
    DISCUSSION_SECTION = "discussion_section"
    PAPER_DRAFT = "paper_draft"
    PROPOSAL = "proposal"
    REVIEW = "review"
    COPYRIGHT_MATERIALS = "copyright_materials"
    TECHNICAL_DESCRIPTION = "technical_description"
    PATENT_OUTLINE = "patent_outline"
    PRIOR_ART_REPORT = "prior_art_report"
    PAPER_ANALYSIS = "paper_analysis"
    LITERATURE_SEARCH_RESULTS = "literature_search_results"
    BACKGROUND_RESEARCH = "background_research"
    OPENING_REPORT = "opening_report"
    FEASIBILITY_ANALYSIS = "feasibility_analysis"
    LITERATURE_INVENTORY = "literature_inventory"
    THESIS_CHAPTER = "thesis_chapter"
    GAP_ANALYSIS = "gap_analysis"
