# src/thesis/workflow/latex_template.py
"""LaTeX template utilities for thesis generation."""

# Chinese thesis template using ctexart
THESIS_TEMPLATE = r"""% 本科毕业设计论文
% Generated by AcademiaGPT

\documentclass[UTF8, a4paper, 12pt, openany]{{ctexart}}

% Page geometry
\usepackage{{geometry}}
\geometry{{left=2.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm}}

% Essential packages
\usepackage{{graphicx}}
\usepackage{{amsmath, amssymb}}
\usepackage{{booktabs}}
\usepackage{{hyperref}}
\usepackage{{xcolor}}
\usepackage{{listings}}
\usepackage{{float}}

% Code listing style
\lstset{{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny,
}}

% Hyperref setup
\hypersetup{{
    colorlinks=true,
    linkcolor=blue,
    citecolor=blue,
    urlcolor=blue,
}}

% Title information
\title{{{title}}}
\author{{{author}}}
\date{{\today}}

\begin{{document}}

\maketitle

% Abstract
{abstract}

% Table of contents
\newpage
\tableofcontents

% Main content
{content}

% Bibliography
\newpage
\bibliographystyle{{gbt7714}}
\bibliography{{refs}}

% Acknowledgements
\newpage
\section*{{致谢}}
{acknowledgements}

\end{{document}}
"""


def get_template(language: str = "zh") -> str:
    """Get LaTeX template by language.

    Args:
        language: "zh" for Chinese, "en" for English

    Returns:
        LaTeX template string
    """
    return THESIS_TEMPLATE if language == "zh" else THESIS_TEMPLATE
