"""Shared dataclasses for feature bridge flows."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class BridgedChatResponse:
    """Structured chat reply generated by the deterministic feature bridge."""

    content: str
    blocks: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
