"""Update workspace types to match frontend

Revision ID: ac1b3eebecbf
Revises: 002_task_records
Create Date: 2026-03-11 17:13:40.949237+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac1b3eebecbf'
down_revision: Union[str, None] = '002_task_records'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('cited_paper_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('citation_type', sa.String(length=20), nullable=False),
    sa.Column('citation_context', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'cited_paper_id', 'workspace_id', name='uq_citation_relationship')
    )
    op.create_index('ix_citations_source', 'citations', ['paper_id'], unique=False)
    op.create_index('ix_citations_target', 'citations', ['cited_paper_id'], unique=False)
    op.create_index('ix_citations_workspace', 'citations', ['workspace_id'], unique=False)
    op.create_table('paper_sections',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=False),
    sa.Column('section_path', sa.String(length=50), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_sections_paper_workspace', 'paper_sections', ['paper_id', 'workspace_id'], unique=False)
    op.create_index('ix_paper_sections_path', 'paper_sections', ['paper_id', 'section_path'], unique=False)
    op.drop_index(op.f('idx_lit_sections_lit_id'), table_name='literature_sections')
    op.drop_index(op.f('idx_lit_sections_lit_seq'), table_name='literature_sections')
    op.drop_table('literature_sections')
    op.drop_index(op.f('idx_literatures_doi'), table_name='literatures')
    op.drop_index(op.f('idx_literatures_is_core'), table_name='literatures')
    op.drop_index(op.f('idx_literatures_workspace_id'), table_name='literatures')
    op.drop_table('literatures')
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_artifacts_parent', 'artifacts', ['parent_artifact_id'], unique=False)
    op.drop_constraint(op.f('artifacts_parent_artifact_id_fkey'), 'artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'artifacts', 'artifacts', ['parent_artifact_id'], ['id'], ondelete='SET NULL')
    op.alter_column('generation_records', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('generation_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('paper_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_paper_chunks_embedding'), table_name='paper_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('paper_chunks', 'embedding')
    op.alter_column('paper_extractions', 'structured_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('paper_extractions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_extractions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_paper_extractions_paper'), table_name='paper_extractions')
    op.create_index(op.f('ix_paper_extractions_paper_id'), 'paper_extractions', ['paper_id'], unique=False)
    op.add_column('papers', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('papers', sa.Column('toc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('papers', 'authors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('papers', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'manual_upload'::character varying"))
    op.alter_column('papers', 'external_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('papers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('papers_doi_key'), 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.alter_column('user_knowledge', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PREFERENCE', 'KNOWLEDGE', 'CONTEXT', 'BEHAVIOR', 'GOAL', name='knowledgecategory'),
               existing_nullable=False)
    op.alter_column('user_knowledge', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_knowledge', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('workspace_papers', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('workspace_papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_papers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_workspace_paper', 'workspace_papers', ['workspace_id', 'paper_id'])
    op.alter_column('workspaces', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workspaces_user'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_user'), 'workspaces', ['user_id'], unique=False)
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('uq_workspace_paper', 'workspace_papers', type_='unique')
    op.alter_column('workspace_papers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_papers', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_knowledge', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_knowledge', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_knowledge', 'category',
               existing_type=sa.Enum('PREFERENCE', 'KNOWLEDGE', 'CONTEXT', 'BEHAVIOR', 'GOAL', name='knowledgecategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_unique_constraint(op.f('papers_doi_key'), 'papers', ['doi'], postgresql_nulls_not_distinct=False)
    op.alter_column('papers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('papers', 'external_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('papers', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'manual_upload'::character varying"))
    op.alter_column('papers', 'authors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('papers', 'toc')
    op.drop_column('papers', 'source_url')
    op.drop_index(op.f('ix_paper_extractions_paper_id'), table_name='paper_extractions')
    op.create_index(op.f('ix_paper_extractions_paper'), 'paper_extractions', ['paper_id'], unique=False)
    op.alter_column('paper_extractions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_extractions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_extractions', 'structured_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('paper_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_paper_chunks_embedding'), 'paper_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('paper_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('paper_chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('generation_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_records', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('artifacts_parent_artifact_id_fkey'), 'artifacts', 'artifacts', ['parent_artifact_id'], ['id'])
    op.drop_index('ix_artifacts_parent', table_name='artifacts')
    op.alter_column('artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('literatures',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publication_source', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('volume', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issue', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pages', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('literature_type', sa.VARCHAR(length=50), server_default=sa.text("'journal'::character varying"), autoincrement=False, nullable=True),
    sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_core', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('impact_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_open_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('citation_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=True),
    sa.Column('llm_extraction_status', sa.VARCHAR(length=20), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sub_domain', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('toc_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('toc_extraction_status', sa.VARCHAR(length=20), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_literatures_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('literatures_pkey'))
    )
    op.create_index(op.f('idx_literatures_workspace_id'), 'literatures', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_literatures_is_core'), 'literatures', ['is_core'], unique=False)
    op.create_index(op.f('idx_literatures_doi'), 'literatures', ['doi'], unique=False)
    op.create_table('literature_sections',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('literature_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('start_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['literature_id'], ['literatures.id'], name=op.f('fk_lit_sections_literature'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('literature_sections_pkey'))
    )
    op.create_index(op.f('idx_lit_sections_lit_seq'), 'literature_sections', ['literature_id', 'sequence'], unique=False)
    op.create_index(op.f('idx_lit_sections_lit_id'), 'literature_sections', ['literature_id'], unique=False)
    op.drop_index('ix_paper_sections_path', table_name='paper_sections')
    op.drop_index('ix_paper_sections_paper_workspace', table_name='paper_sections')
    op.drop_table('paper_sections')
    op.drop_index('ix_citations_workspace', table_name='citations')
    op.drop_index('ix_citations_target', table_name='citations')
    op.drop_index('ix_citations_source', table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
