"""LaTeX template utilities for thesis generation."""

THESIS_TEMPLATE_ZH = r"""% 本科毕业设计论文
% Generated by Wenjin

\documentclass[UTF8, a4paper, 12pt, openany]{{ctexart}}

% Page geometry
\usepackage{{geometry}}
\geometry{{left=2.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm}}

% Essential packages
\usepackage{{graphicx}}
\usepackage{{amsmath, amssymb}}
\usepackage{{booktabs}}
\usepackage{{hyperref}}
\usepackage{{xcolor}}
\usepackage{{listings}}
\usepackage{{float}}

% Code listing style
\lstset{{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny,
}}

% Hyperref setup
\hypersetup{{
    colorlinks=true,
    linkcolor=blue,
    citecolor=blue,
    urlcolor=blue,
}}

% Title information
\title{{{title}}}
\author{{{author}}}
\date{{\today}}

\begin{{document}}

\maketitle

% Abstract
{abstract}

% Table of contents
\newpage
\tableofcontents

% Main content
{content}

% Bibliography
\newpage
\bibliographystyle{{gbt7714}}
\bibliography{{refs}}

% Acknowledgements
\newpage
\section*{{致谢}}
{acknowledgements}

\end{{document}}
"""

THESIS_TEMPLATE_EN = r"""% Undergraduate Thesis
% Generated by Wenjin

\documentclass[a4paper, 12pt, openany]{{article}}

% Page geometry
\usepackage{{geometry}}
\geometry{{left=1in, right=1in, top=1in, bottom=1in}}

% Essential packages
\usepackage{{graphicx}}
\usepackage{{amsmath, amssymb}}
\usepackage{{booktabs}}
\usepackage{{hyperref}}
\usepackage{{xcolor}}
\usepackage{{listings}}
\usepackage{{float}}

% Code listing style
\lstset{{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny,
}}

% Hyperref setup
\hypersetup{{
    colorlinks=true,
    linkcolor=blue,
    citecolor=blue,
    urlcolor=blue,
}}

% Title information
\title{{{title}}}
\author{{{author}}}
\date{{\today}}

\begin{{document}}

\maketitle

% Abstract
{abstract}

% Table of contents
\newpage
\tableofcontents

% Main content
{content}

% Bibliography
\newpage
\bibliographystyle{{plain}}
\bibliography{{refs}}

% Acknowledgements
\newpage
\section*{{Acknowledgements}}
{acknowledgements}

\end{{document}}
"""

__all__ = ["THESIS_TEMPLATE_ZH", "THESIS_TEMPLATE_EN", "get_template"]


def get_template(language: str = "zh") -> str:
    """Get LaTeX template by language."""
    if language == "en":
        return THESIS_TEMPLATE_EN
    return THESIS_TEMPLATE_ZH
