"""CriticalWriter subagent — V1 stub that generates a templated critical synthesis markdown."""

from ..base import SubagentBase, SubagentContext, SubagentResult
from ..registry import subagent


@subagent("critical_writer")
class CriticalWriter(SubagentBase):
    """Writes a critical synthesis section from thematic clusters.

    Required inputs:
        clusters (list[dict]): Thematic clusters, each with 'theme' and 'paper_ids'.

    Optional inputs:
        style (str): Citation/writing style, e.g. 'academic', 'narrative'. Defaults to 'academic'.

    Output shape::

        {"markdown": str}

    V1 stub: returns a templated markdown string that names each theme cluster.
    """

    allowed_tools = []

    async def run(self, ctx: SubagentContext) -> SubagentResult:
        clusters = ctx.inputs.get("clusters")
        if clusters is None:
            raise ValueError("critical_writer requires 'clusters' in inputs")
        if not isinstance(clusters, list):
            raise ValueError("critical_writer: 'clusters' must be a list")

        style = ctx.inputs.get("style", "academic")

        sections: list[str] = []
        sections.append("# Critical Synthesis\n")
        sections.append(f"> *Style: {style}*\n")
        sections.append(
            "This section critically synthesises the existing literature, "
            "organised by thematic cluster.\n"
        )

        for cluster in clusters:
            theme = cluster.get("theme", "Unknown Theme")
            paper_ids = cluster.get("paper_ids", [])
            paper_list = "\n".join(f"- `{pid}`" for pid in paper_ids) if paper_ids else "- *(no papers)*"
            sections.append(f"\n## {theme}\n")
            sections.append(
                f"The following works contribute to the theme of **{theme}**:\n\n"
                f"{paper_list}\n\n"
                f"[V1 stub — real synthesis will be generated by LLM in Phase 2.]\n"
            )

        sections.append("\n## Summary\n")
        sections.append(
            "Across the identified clusters, the literature demonstrates both convergent "
            "and divergent research trajectories. [V1 stub — real summary pending.]\n"
        )

        markdown = "\n".join(sections)

        return SubagentResult(
            output={"markdown": markdown},
            tool_calls=[],
            token_usage={"input": 0, "output": 0},
        )
