import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  header: {
    height: 58,
    flexShrink: 0,
    display: "grid",
    gridTemplateColumns: "minmax(140px, 190px) minmax(220px, 1fr) auto",
    alignItems: "center",
    gap: 10,
    padding: "9px 14px",
    borderBottom: "1px solid var(--wjn-line)",
    background: "rgba(255, 255, 255, 0.82)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
  },
  eyebrow: {
    fontSize: 10.5,
    color: "var(--wjn-text-muted)",
    fontWeight: 650,
  },
  headerTitle: {
    fontSize: 15,
    lineHeight: 1.3,
    fontWeight: 750,
    color: "var(--wjn-text)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerMiddle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    minWidth: 0,
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    minWidth: 0,
  },
  tabButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 32,
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--wjn-text-secondary)",
    fontSize: 13,
    fontWeight: 650,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  tabButtonActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-accent-strong)",
  },
  tabButtonExpanded: {
    minWidth: 72,
    padding: "0 10px",
  },
  tabButtonIconOnly: {
    width: 34,
    padding: 0,
    justifyContent: "center",
  },
  tabBadge: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    padding: "0 5px",
    background: "rgba(20, 20, 30, 0.08)",
    color: "var(--v2-text-secondary)",
    fontSize: 10,
    lineHeight: "16px",
  },
  statusPill: {
    display: "inline-flex",
    alignItems: "center",
    height: 24,
    padding: "0 9px",
    borderRadius: 8,
    fontSize: 11.5,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  iconTextButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "rgba(255, 255, 255, 0.72)",
    color: "var(--v2-text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  iconButtonCompact: {
    width: 32,
    padding: 0,
  },
  iconButton: {
    width: 32,
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "rgba(255, 255, 255, 0.72)",
    color: "var(--v2-text-secondary)",
    cursor: "pointer",
  },
  miniStatus: {
    maxWidth: 180,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 11.5,
    color: "var(--v2-text-tertiary)",
  },
  interventionBar: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto auto",
    gap: 10,
    alignItems: "center",
    padding: "10px 16px",
    borderBottom: "1px solid rgba(20, 20, 30, 0.08)",
    background: "rgba(255,255,255,0.72)",
  },
  interventionInput: {
    width: "100%",
    resize: "vertical",
    minHeight: 44,
    maxHeight: 120,
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.1)",
    background: "rgba(255,255,255,0.9)",
    color: "var(--v2-text-primary)",
    fontSize: 13,
    lineHeight: 1.45,
    outline: "none",
  },
  interventionStatus: {
    fontSize: 12,
    color: "var(--v2-text-tertiary)",
    whiteSpace: "nowrap",
  },
  body: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: 16,
  },
  viewStack: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    maxWidth: 1200,
    margin: "0 auto",
  },
  section: {
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "rgba(255, 255, 255, 0.78)",
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.06)",
    padding: 14,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  sectionHeaderCompact: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    lineHeight: 1.35,
    fontWeight: 750,
    color: "var(--v2-text-primary)",
  },
  sectionTitleSmall: {
    fontSize: 13,
    fontWeight: 750,
    color: "var(--v2-text-primary)",
    marginBottom: 2,
  },
  sectionSubtitle: {
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--v2-text-tertiary)",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 10,
  },
  metricCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "rgba(255,255,255,0.78)",
    padding: 12,
  },
  metricValue: {
    fontSize: 20,
    lineHeight: 1,
    fontWeight: 800,
    color: "var(--v2-text-primary)",
  },
  metricLabel: {
    marginTop: 4,
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--v2-text-secondary)",
  },
  metricDetail: {
    marginTop: 2,
    fontSize: 11.5,
    color: "var(--v2-text-tertiary)",
  },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 10,
  },
  featureButton: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    minHeight: 72,
    padding: 12,
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "rgba(255,255,255,0.76)",
    color: "var(--v2-text-primary)",
    textAlign: "left",
    cursor: "pointer",
  },
  featureTitle: {
    display: "block",
    fontSize: 13.5,
    fontWeight: 750,
    color: "var(--v2-text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  featureDescription: {
    display: "block",
    marginTop: 4,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--v2-text-tertiary)",
  },
  runList: {
    display: "grid",
    gap: 8,
  },
  runListItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.75)",
    textAlign: "left",
    cursor: "pointer",
  },
  runListMain: {
    minWidth: 0,
    display: "grid",
    gap: 2,
  },
  runListTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--v2-text-primary)",
    fontSize: 13.5,
    fontWeight: 700,
  },
  runListMeta: {
    color: "var(--v2-text-tertiary)",
    fontSize: 12,
  },
  runGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))",
    gap: 14,
    minHeight: "100%",
  },
  runMain: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  },
  runPrimarySection: {
    display: "grid",
    gap: 14,
  },
  cockpitHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  cockpitActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  progressOuter: {
    height: 8,
    borderRadius: 8,
    overflow: "hidden",
    background: "rgba(20,20,30,0.08)",
  },
  progressInner: {
    height: "100%",
    borderRadius: 8,
    background: "linear-gradient(90deg, #7C3AED, #2563EB)",
    transition: "width 220ms ease",
  },
  progressMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
    color: "var(--v2-text-tertiary)",
    fontSize: 12,
  },
  quickActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  teamPanel: {
    display: "grid",
    gap: 10,
    paddingTop: 13,
    borderTop: "1px solid rgba(20,20,30,0.08)",
  },
  teamTitleLine: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
    color: "var(--v2-text-primary)",
  },
  teamRows: {
    display: "grid",
    gap: 0,
    borderTop: "1px solid rgba(20,20,30,0.06)",
  },
  teamRow: {
    display: "grid",
    gridTemplateColumns: "minmax(150px, 1fr) minmax(0, 1.2fr) auto",
    alignItems: "center",
    gap: 10,
    minHeight: 46,
    padding: "8px 0",
    borderBottom: "1px solid rgba(20,20,30,0.06)",
  },
  teamMemberMain: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  teamMemberName: {
    color: "var(--v2-text-primary)",
    fontSize: 13,
    fontWeight: 750,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  teamMemberMeta: {
    marginTop: 2,
    color: "var(--v2-text-tertiary)",
    fontSize: 11.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  teamChipWrap: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 5,
    minWidth: 0,
  },
  teamChip: {
    maxWidth: 150,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    borderRadius: 8,
    border: "1px solid rgba(37, 99, 235, 0.14)",
    background: "rgba(37, 99, 235, 0.07)",
    color: "#1D4ED8",
    padding: "3px 6px",
    fontSize: 11,
    fontWeight: 650,
  },
  gateStrip: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  gateItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minHeight: 26,
    padding: "3px 4px 3px 8px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.62)",
  },
  gateName: {
    maxWidth: 190,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--v2-text-secondary)",
    fontSize: 11.5,
    fontWeight: 650,
  },
  gateBadge: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    padding: "0 7px",
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 750,
  },
  timelinePanel: {
    paddingTop: 13,
    borderTop: "1px solid rgba(20,20,30,0.08)",
  },
  timeline: {
    display: "grid",
    gap: 12,
  },
  phaseBlock: {
    display: "grid",
    gap: 8,
  },
  phaseTitle: {
    fontSize: 12,
    fontWeight: 750,
    color: "var(--v2-text-tertiary)",
  },
  nodeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 8,
  },
  nodeButton: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 38,
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.72)",
    cursor: "pointer",
    textAlign: "left",
  },
  nodeButtonActive: {
    border: "1px solid rgba(124, 58, 237, 0.24)",
    background: "rgba(124, 58, 237, 0.08)",
  },
  nodeButtonText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--v2-text-primary)",
  },
  nodeDot: {
    width: 16,
    height: 16,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  inspector: {
    minWidth: 0,
  },
  nodeInspector: {
    position: "sticky",
    top: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.8)",
    padding: 14,
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.06)",
  },
  nodeMetaLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--v2-text-tertiary)",
    fontSize: 12,
  },
  inspectorBlock: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(248,250,252,0.82)",
    padding: 10,
  },
  inspectorBlockTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 7,
    fontSize: 12,
    fontWeight: 750,
    color: "var(--v2-text-secondary)",
  },
  pre: {
    margin: 0,
    maxHeight: 180,
    overflow: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontSize: 11.5,
    lineHeight: 1.5,
    color: "var(--v2-text-secondary)",
    fontFamily: "var(--v2-font-mono)",
  },
  toolList: {
    display: "grid",
    gap: 6,
  },
  toolItem: {
    display: "grid",
    gap: 2,
    padding: "7px 8px",
    borderRadius: 8,
    background: "rgba(255,255,255,0.78)",
  },
  toolName: {
    fontSize: 12,
    fontWeight: 750,
    color: "var(--v2-text-primary)",
  },
  toolMeta: {
    fontSize: 11.5,
    color: "var(--v2-text-tertiary)",
  },
  sandboxSummary: {
    display: "grid",
    gap: 5,
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--v2-text-secondary)",
  },
  evidenceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))",
    gap: 14,
    minHeight: "100%",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  searchBox: {
    flex: 1,
    minWidth: 220,
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: 36,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.78)",
    color: "var(--v2-text-tertiary)",
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    border: "none",
    background: "transparent",
    outline: "none",
    color: "var(--v2-text-primary)",
    fontSize: 13,
  },
  segmented: {
    display: "inline-flex",
    alignItems: "center",
    padding: 3,
    borderRadius: 8,
    background: "rgba(20,20,30,0.06)",
  },
  segmentButton: {
    height: 28,
    padding: "0 9px",
    border: "none",
    borderRadius: 7,
    background: "transparent",
    color: "var(--v2-text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  segmentButtonActive: {
    background: "rgba(255,255,255,0.9)",
    color: "var(--v2-accent-purple-700)",
    boxShadow: "0 1px 4px rgba(15,23,42,0.08)",
  },
  evidenceTableWrap: {
    overflow: "auto",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
  },
  evidenceTable: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: 720,
    background: "rgba(255,255,255,0.82)",
  },
  th: {
    padding: "9px 10px",
    borderBottom: "1px solid rgba(20,20,30,0.08)",
    textAlign: "left",
    color: "var(--v2-text-tertiary)",
    fontSize: 11.5,
    fontWeight: 750,
  },
  tr: {
    cursor: "pointer",
    borderBottom: "1px solid rgba(20,20,30,0.06)",
  },
  trSelected: {
    background: "rgba(124, 58, 237, 0.07)",
  },
  td: {
    padding: "9px 10px",
    fontSize: 12.5,
    color: "var(--v2-text-secondary)",
    verticalAlign: "top",
  },
  tdStrong: {
    padding: "9px 10px",
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--v2-text-primary)",
    verticalAlign: "top",
  },
  tdMuted: {
    padding: "9px 10px",
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--v2-text-tertiary)",
    verticalAlign: "top",
  },
  readOnlyMark: {
    fontSize: 11,
    color: "var(--v2-text-tertiary)",
  },
  editorAside: {
    minWidth: 0,
  },
  reviewGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(280px, 0.86fr) minmax(420px, 1.14fr)",
    gap: 14,
    minHeight: "100%",
    alignItems: "start",
    overflowX: "auto",
  },
  reviewGridSingle: {
    gridTemplateColumns: "minmax(0, 1fr)",
    overflowX: "hidden",
  },
  reviewInbox: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.78)",
    padding: 12,
    minWidth: 0,
    maxHeight: "calc(100vh - 150px)",
    overflow: "auto",
  },
  reviewDetail: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minWidth: 0,
    position: "sticky",
    top: 0,
    maxHeight: "calc(100vh - 150px)",
    overflow: "auto",
  },
  previewList: {
    display: "grid",
    gap: 10,
  },
  reviewFilterBar: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 0 10px",
    overflowX: "auto",
  },
  reviewFilterButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    height: 26,
    padding: "0 9px",
    borderRadius: 999,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.66)",
    color: "var(--v2-text-secondary)",
    fontSize: 11.5,
    fontWeight: 750,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  reviewFilterButtonActive: {
    borderColor: "rgba(124, 58, 237, 0.22)",
    background: "rgba(124, 58, 237, 0.08)",
    color: "var(--v2-accent-purple-700)",
  },
  filterCount: {
    fontSize: 10.5,
    fontVariantNumeric: "tabular-nums",
    opacity: 0.72,
  },
  previewGroupCompact: {
    display: "grid",
    gap: 7,
  },
  previewGroupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 22,
    padding: "0 2px",
  },
  previewGroupTitle: {
    fontSize: 12,
    fontWeight: 750,
  },
  previewGroupCount: {
    minWidth: 22,
    height: 20,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    border: "1px solid",
    fontSize: 11,
    fontWeight: 750,
    fontVariantNumeric: "tabular-nums",
  },
  previewGroupList: {
    display: "grid",
    gap: 8,
  },
  previewListItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    minWidth: 0,
    overflow: "hidden",
    padding: 10,
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.72)",
  },
  previewListItemActive: {
    border: "1px solid rgba(124, 58, 237, 0.24)",
    background: "rgba(124, 58, 237, 0.07)",
  },
  previewListButton: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    border: "none",
    padding: 0,
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
  },
  previewTitle: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--v2-text-primary)",
    fontSize: 13,
    fontWeight: 750,
  },
  previewMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 6,
    minWidth: 0,
    overflow: "hidden",
    marginTop: 4,
    color: "var(--v2-text-tertiary)",
    fontSize: 11.5,
  },
  previewSubtitleInline: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  kindBadge: {
    height: 20,
    minWidth: 48,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 7px",
    borderRadius: 999,
    border: "1px solid",
    fontSize: 11,
    fontWeight: 750,
    lineHeight: 1,
    whiteSpace: "nowrap",
  },
  commitBox: {
    marginTop: 12,
    paddingTop: 12,
    borderTop: "1px solid rgba(20,20,30,0.08)",
  },
  prismBox: {
    marginTop: 12,
    padding: 10,
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(248,250,252,0.82)",
  },
  countBadge: {
    minWidth: 24,
    height: 22,
    padding: "0 8px",
    borderRadius: 8,
    background: "rgba(20,20,30,0.06)",
    color: "var(--v2-text-secondary)",
    fontSize: 12,
    fontWeight: 750,
    lineHeight: "22px",
    textAlign: "center",
  },
  editorPanel: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.82)",
    padding: 14,
  },
  fieldLabel: {
    display: "grid",
    gap: 6,
    marginTop: 10,
    fontSize: 12,
    fontWeight: 700,
    color: "var(--v2-text-secondary)",
  },
  textInput: {
    width: "100%",
    height: 36,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.1)",
    background: "rgba(255,255,255,0.9)",
    color: "var(--v2-text-primary)",
    fontSize: 13,
    outline: "none",
  },
  textArea: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.1)",
    background: "rgba(255,255,255,0.9)",
    color: "var(--v2-text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
    resize: "vertical",
    outline: "none",
  },
  checkbox: {
    marginTop: 3,
    accentColor: "var(--v2-accent-purple-700)",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: 36,
    padding: "0 13px",
    borderRadius: 8,
    border: "1px solid var(--v2-accent-purple-700)",
    background: "var(--v2-accent-purple-700)",
    color: "#fff",
    fontSize: 12.5,
    fontWeight: 750,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 34,
    padding: "0 11px",
    borderRadius: 8,
    border: "1px solid rgba(124, 58, 237, 0.18)",
    background: "rgba(124, 58, 237, 0.08)",
    color: "var(--v2-accent-purple-700)",
    fontSize: 12.5,
    fontWeight: 750,
    cursor: "pointer",
  },
  ghostButton: {
    height: 30,
    padding: "0 9px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "rgba(255,255,255,0.72)",
    color: "var(--v2-text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  },
  commitError: {
    marginTop: 10,
    padding: "8px 10px",
    borderRadius: 8,
    background: "rgba(220, 38, 38, 0.06)",
    border: "1px solid rgba(220, 38, 38, 0.12)",
    color: "var(--v2-status-error)",
    fontSize: 12,
  },
  linkWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  roomLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 9px",
    borderRadius: 8,
    background: "var(--v2-accent-purple-100)",
    color: "var(--v2-accent-purple-700)",
    fontSize: 11.5,
    fontWeight: 650,
    textDecoration: "none",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: 150,
    textAlign: "center",
    borderRadius: 8,
    border: "1px dashed rgba(20,20,30,0.12)",
    background: "rgba(255,255,255,0.5)",
  },
  emptyTitle: {
    fontSize: 13.5,
    fontWeight: 750,
    color: "var(--v2-text-secondary)",
  },
  emptyDetail: {
    maxWidth: 420,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--v2-text-tertiary)",
  },
};
