import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  header: {
    height: 58,
    flexShrink: 0,
    display: "grid",
    gridTemplateColumns: "minmax(140px, 190px) minmax(220px, 1fr) auto",
    alignItems: "center",
    gap: 10,
    padding: "9px 14px",
    borderBottom: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface)",
  },
  eyebrow: {
    fontSize: 10.5,
    color: "var(--wjn-text-muted)",
    fontWeight: 650,
  },
  headerTitle: {
    fontSize: 15,
    lineHeight: 1.3,
    fontWeight: 750,
    color: "var(--wjn-text)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerMiddle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    minWidth: 0,
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    minWidth: 0,
  },
  tabButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 32,
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--wjn-text-secondary)",
    fontSize: 13,
    fontWeight: 650,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  tabButtonActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-accent-strong)",
  },
  tabButtonExpanded: {
    minWidth: 72,
    padding: "0 10px",
  },
  tabButtonIconOnly: {
    width: 34,
    padding: 0,
    justifyContent: "center",
  },
  tabBadge: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    padding: "0 5px",
    background: "rgba(20, 20, 30, 0.08)",
    color: "var(--wjn-text-secondary)",
    fontSize: 10,
    lineHeight: "16px",
  },
  statusPill: {
    display: "inline-flex",
    alignItems: "center",
    height: 24,
    padding: "0 9px",
    borderRadius: 8,
    fontSize: 11.5,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  iconTextButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  iconButton: {
    width: 32,
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    cursor: "pointer",
  },
  miniStatus: {
    maxWidth: 180,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 11.5,
    color: "var(--wjn-text-muted)",
  },
  interventionBar: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto auto",
    gap: 10,
    alignItems: "center",
    padding: "10px 16px",
    borderBottom: "1px solid rgba(20, 20, 30, 0.08)",
    background: "var(--wjn-surface)",
  },
  interventionInput: {
    width: "100%",
    resize: "vertical",
    minHeight: 44,
    maxHeight: 120,
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.1)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text)",
    fontSize: 13,
    lineHeight: 1.45,
    outline: "none",
  },
  interventionStatus: {
    fontSize: 12,
    color: "var(--wjn-text-muted)",
    whiteSpace: "nowrap",
  },
  body: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: 16,
  },
  viewStack: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    maxWidth: 1200,
    margin: "0 auto",
  },
  section: {
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "var(--wjn-surface)",
    boxShadow: "var(--wjn-shadow-sm)",
    padding: 14,
  },
  primarySection: {
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "var(--wjn-surface)",
    boxShadow: "var(--wjn-shadow-sm)",
    padding: 14,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  sectionHeaderCompact: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    lineHeight: 1.35,
    fontWeight: 750,
    color: "var(--wjn-text)",
  },
  sectionTitleSmall: {
    fontSize: 13,
    fontWeight: 750,
    color: "var(--wjn-text)",
    marginBottom: 2,
  },
  sectionSubtitle: {
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--wjn-text-muted)",
  },
  summaryStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 150px), 1fr))",
    gap: 8,
  },
  metricCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 8,
    border: "1px solid rgba(20, 20, 30, 0.08)",
    background: "var(--wjn-surface)",
    padding: 12,
  },
  metricValue: {
    fontSize: 20,
    lineHeight: 1,
    fontWeight: 800,
    color: "var(--wjn-text)",
  },
  metricLabel: {
    marginTop: 4,
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--wjn-text-secondary)",
  },
  metricDetail: {
    marginTop: 2,
    fontSize: 11.5,
    color: "var(--wjn-text-muted)",
  },
  missionConsole: {
    display: "grid",
    gap: 14,
  },
  missionHeader: {
    display: "grid",
    gap: 6,
  },
  missionLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    color: "var(--wjn-text-muted)",
  },
  missionTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  missionTitle: {
    fontSize: 17,
    lineHeight: 1.35,
    fontWeight: 750,
    color: "var(--wjn-text)",
  },
  missionGoal: {
    fontSize: 13,
    lineHeight: 1.6,
    color: "var(--wjn-text-secondary)",
  },
  missionStageRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  missionStageChip: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 28,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    fontWeight: 650,
  },
  missionStageChipActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-accent-strong)",
  },
  missionStageChipDone: {
    border: "1px solid var(--wjn-success)",
    background: "var(--wjn-success-soft)",
    color: "var(--wjn-success)",
  },
  missionStageChipReview: {
    border: "1px solid var(--wjn-review)",
    background: "var(--wjn-review-soft)",
    color: "var(--wjn-review)",
  },
  missionStageChipBlocked: {
    border: "1px solid var(--wjn-error)",
    background: "var(--wjn-error-soft)",
    color: "var(--wjn-error)",
  },
  missionNextAction: {
    display: "grid",
    gap: 4,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface-subtle)",
  },
  missionNextActionText: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--wjn-text-secondary)",
  },
  missionIdleState: {
    display: "grid",
    gap: 6,
    padding: "10px 0 2px",
  },
  missionActionRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  missionActionButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12.5,
    fontWeight: 650,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  guidanceNote: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    lineHeight: 1.45,
  },
  guidanceNoteWarning: {
    border: "1px solid rgba(198, 138, 26, 0.16)",
    background: "var(--wjn-review-soft)",
    color: "var(--wjn-review)",
  },
  runList: {
    display: "grid",
    gap: 8,
  },
  runListItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    textAlign: "left",
    cursor: "pointer",
  },
  runListMain: {
    minWidth: 0,
    display: "grid",
    gap: 2,
  },
  runListTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--wjn-text)",
    fontSize: 13.5,
    fontWeight: 700,
  },
  runListMeta: {
    color: "var(--wjn-text-muted)",
    fontSize: 12,
  },
  runGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))",
    gap: 14,
    minHeight: "100%",
  },
  runStack: {
    display: "grid",
    gap: 14,
    minHeight: "100%",
    maxWidth: 1120,
    margin: "0 auto",
  },
  runMain: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  },
  runPrimarySection: {
    display: "grid",
    gap: 14,
  },
  cockpitHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  cockpitActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  progressOuter: {
    height: 8,
    borderRadius: 8,
    overflow: "hidden",
    background: "rgba(15,31,53,0.08)",
  },
  progressInner: {
    width: "100%",
    height: "100%",
    borderRadius: 8,
    background: "var(--wjn-blue)",
    transformOrigin: "left center",
    transition: "transform 220ms var(--wjn-ease-standard)",
  },
  progressMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
    color: "var(--wjn-text-muted)",
    fontSize: 12,
  },
  quickActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  writebackBox: {
    display: "grid",
    gap: 8,
    marginTop: 10,
    padding: "10px 11px",
    borderRadius: 10,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface)",
  },
  writebackMain: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "var(--wjn-success)",
    fontSize: 12.5,
    fontWeight: 750,
  },
  writebackActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  writebackError: {
    color: "var(--wjn-error)",
    fontSize: 12,
    lineHeight: 1.45,
  },
  writebackLinks: {
    display: "flex",
    flexWrap: "wrap",
    gap: 7,
  },
  writebackLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minHeight: 28,
    padding: "0 8px",
    borderRadius: 8,
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-blue)",
    fontSize: 12,
    fontWeight: 650,
    textDecoration: "none",
  },
  teamPanel: {
    display: "grid",
    gap: 10,
    padding: 13,
    borderRadius: 14,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface)",
    boxShadow: "var(--wjn-shadow-sm)",
  },
  teamTitleLine: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
    color: "var(--wjn-text)",
  },
  teamRows: {
    display: "grid",
    gap: 8,
  },
  teamRow: {
    display: "grid",
    gridTemplateColumns: "minmax(150px, 1fr) auto",
    alignItems: "center",
    gap: 10,
    minHeight: 46,
    padding: "9px 10px",
    borderRadius: 12,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface)",
  },
  teamMemberMain: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  teamStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    flexShrink: 0,
  },
  teamMemberName: {
    color: "var(--wjn-text)",
    fontSize: 13,
    fontWeight: 750,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  teamMemberMeta: {
    marginTop: 2,
    color: "var(--wjn-text-muted)",
    fontSize: 11.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  teamChipWrap: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 5,
    minWidth: 0,
  },
  teamChip: {
    maxWidth: 150,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    borderRadius: 8,
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-blue-strong)",
    padding: "3px 6px",
    fontSize: 11,
    fontWeight: 650,
  },
  gateStrip: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  gateItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minHeight: 26,
    padding: "3px 4px 3px 8px",
    borderRadius: 8,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface-subtle)",
  },
  gateName: {
    maxWidth: 190,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--wjn-text-secondary)",
    fontSize: 11.5,
    fontWeight: 650,
  },
  gateBadge: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    padding: "0 7px",
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 750,
  },
  timelinePanel: {
    paddingTop: 13,
    borderTop: "1px solid rgba(20,20,30,0.08)",
  },
  timeline: {
    display: "grid",
    gap: 12,
  },
  phaseBlock: {
    display: "grid",
    gap: 8,
  },
  phaseTitle: {
    fontSize: 12,
    fontWeight: 750,
    color: "var(--wjn-text-muted)",
  },
  nodeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 8,
  },
  progressStepList: {
    display: "grid",
    gap: 7,
  },
  progressStepButton: {
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
    width: "100%",
    minHeight: 46,
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    cursor: "pointer",
    textAlign: "left",
  },
  progressStepButtonActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
  },
  progressStepMain: {
    minWidth: 0,
    display: "grid",
    gap: 2,
  },
  progressStepTitle: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 13,
    fontWeight: 750,
    color: "var(--wjn-text)",
  },
  progressStepDetail: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12,
    lineHeight: 1.4,
    color: "var(--wjn-text-muted)",
  },
  progressStepStatus: {
    fontSize: 11.5,
    fontWeight: 700,
    color: "var(--wjn-text-muted)",
    whiteSpace: "nowrap",
  },
  nodeButton: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 38,
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    cursor: "pointer",
    textAlign: "left",
  },
  nodeButtonActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
  },
  nodeButtonText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--wjn-text)",
  },
  nodeDot: {
    width: 16,
    height: 16,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  inspector: {
    minWidth: 0,
  },
  runDetails: {
    borderTop: "1px solid rgba(20,20,30,0.08)",
    paddingTop: 10,
  },
  runDetailsSummary: {
    cursor: "pointer",
    color: "var(--wjn-text-secondary)",
    fontSize: 12.5,
    fontWeight: 750,
  },
  nodeInspector: {
    marginTop: 10,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    padding: 14,
    boxShadow: "var(--wjn-shadow-sm)",
  },
  nodeMetaLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--wjn-text-muted)",
    fontSize: 12,
  },
  inspectorBlock: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface-subtle)",
    padding: 10,
  },
  inspectorBlockTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 7,
    fontSize: 12,
    fontWeight: 750,
    color: "var(--wjn-text-secondary)",
  },
  pre: {
    margin: 0,
    maxHeight: 180,
    overflow: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontSize: 11.5,
    lineHeight: 1.5,
    color: "var(--wjn-text-secondary)",
    fontFamily: "var(--wjn-font-mono)",
  },
  debugDetails: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    padding: "8px 10px",
  },
  debugSummary: {
    cursor: "pointer",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    fontWeight: 750,
  },
  debugStack: {
    display: "grid",
    gap: 10,
    paddingTop: 10,
  },
  toolList: {
    display: "grid",
    gap: 6,
  },
  toolItem: {
    display: "grid",
    gap: 2,
    padding: "7px 8px",
    borderRadius: 8,
    background: "var(--wjn-surface)",
  },
  toolName: {
    fontSize: 12,
    fontWeight: 750,
    color: "var(--wjn-text)",
  },
  toolMeta: {
    fontSize: 11.5,
    color: "var(--wjn-text-muted)",
  },
  sandboxSummary: {
    display: "grid",
    gap: 5,
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--wjn-text-secondary)",
  },
  evidenceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))",
    gap: 14,
    minHeight: "100%",
  },
  evidenceSummaryPanel: {
    display: "grid",
    gap: 10,
    marginBottom: 12,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--wjn-line)",
    background: "var(--wjn-surface-subtle)",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  searchBox: {
    flex: 1,
    minWidth: 220,
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: 36,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-muted)",
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    border: "none",
    background: "transparent",
    outline: "none",
    color: "var(--wjn-text)",
    fontSize: 13,
  },
  segmented: {
    display: "inline-flex",
    alignItems: "center",
    padding: 3,
    borderRadius: 8,
    background: "rgba(20,20,30,0.06)",
  },
  segmentButton: {
    height: 28,
    padding: "0 9px",
    border: "none",
    borderRadius: 7,
    background: "transparent",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  segmentButtonActive: {
    background: "var(--wjn-surface)",
    color: "var(--wjn-blue)",
    boxShadow: "none",
  },
  evidenceList: {
    display: "grid",
    gap: 8,
  },
  evidenceListItem: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
    width: "100%",
    minHeight: 58,
    padding: "10px 11px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    textAlign: "left",
    cursor: "pointer",
  },
  evidenceListItemActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    boxShadow: "0 0 0 3px rgba(37,99,235,0.05)",
  },
  evidenceListCheck: {
    width: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  evidenceListMain: {
    minWidth: 0,
    display: "grid",
    gap: 4,
  },
  evidenceListTitle: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--wjn-text)",
    fontSize: 13,
    fontWeight: 750,
  },
  evidenceListSummary: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--wjn-text-muted)",
    fontSize: 12,
    lineHeight: 1.4,
  },
  evidenceListKind: {
    display: "inline-flex",
    justifyContent: "flex-end",
    minWidth: 0,
  },
  evidenceTableWrap: {
    overflow: "auto",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
  },
  evidenceTable: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: 720,
    background: "var(--wjn-surface)",
  },
  th: {
    padding: "9px 10px",
    borderBottom: "1px solid rgba(20,20,30,0.08)",
    textAlign: "left",
    color: "var(--wjn-text-muted)",
    fontSize: 11.5,
    fontWeight: 750,
  },
  tr: {
    cursor: "pointer",
    borderBottom: "1px solid rgba(20,20,30,0.06)",
  },
  trSelected: {
    background: "var(--wjn-accent-soft)",
  },
  td: {
    padding: "9px 10px",
    fontSize: 12.5,
    color: "var(--wjn-text-secondary)",
    verticalAlign: "top",
  },
  tdStrong: {
    padding: "9px 10px",
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--wjn-text)",
    verticalAlign: "top",
  },
  tdMuted: {
    padding: "9px 10px",
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--wjn-text-muted)",
    verticalAlign: "top",
  },
  readOnlyMark: {
    fontSize: 11,
    color: "var(--wjn-text-muted)",
  },
  editorAside: {
    minWidth: 0,
  },
  reviewGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 360px), 1fr))",
    gap: 14,
    minHeight: "100%",
    alignItems: "start",
    overflowX: "hidden",
  },
  reviewGridSingle: {
    gridTemplateColumns: "minmax(0, 1fr)",
    overflowX: "hidden",
  },
  reviewInbox: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    padding: 12,
    minWidth: 0,
    maxHeight: "calc(100vh - 150px)",
    overflow: "auto",
  },
  reviewDetail: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minWidth: 0,
    position: "sticky",
    top: 0,
    maxHeight: "calc(100vh - 150px)",
    overflow: "auto",
  },
  previewList: {
    display: "grid",
    gap: 10,
  },
  reviewFilterBar: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 0 10px",
    overflowX: "auto",
  },
  reviewFilterButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    height: 26,
    padding: "0 9px",
    borderRadius: 999,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    fontSize: 11.5,
    fontWeight: 750,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  reviewFilterButtonActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-blue)",
  },
  filterCount: {
    fontSize: 10.5,
    fontVariantNumeric: "tabular-nums",
    opacity: 0.72,
  },
  previewGroupCompact: {
    display: "grid",
    gap: 7,
  },
  previewGroupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 22,
    padding: "0 2px",
  },
  previewGroupTitle: {
    fontSize: 12,
    fontWeight: 750,
  },
  previewGroupCount: {
    minWidth: 22,
    height: 20,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    border: "1px solid",
    fontSize: 11,
    fontWeight: 750,
    fontVariantNumeric: "tabular-nums",
  },
  previewGroupList: {
    display: "grid",
    gap: 8,
  },
  previewListItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    minWidth: 0,
    overflow: "hidden",
    padding: 10,
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
  },
  previewListItemActive: {
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
  },
  previewListButton: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    border: "none",
    padding: 0,
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
  },
  previewTitle: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--wjn-text)",
    fontSize: 13,
    fontWeight: 750,
  },
  previewMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 6,
    minWidth: 0,
    overflow: "hidden",
    marginTop: 4,
    color: "var(--wjn-text-muted)",
    fontSize: 11.5,
  },
  previewSubtitleInline: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  riskBadge: {
    height: 20,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 7px",
    borderRadius: 999,
    border: "1px solid rgba(220, 38, 38, 0.16)",
    background: "rgba(220, 38, 38, 0.08)",
    color: "var(--wjn-error)",
    fontSize: 11,
    fontWeight: 750,
    whiteSpace: "nowrap",
  },
  kindBadge: {
    height: 20,
    minWidth: 48,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 7px",
    borderRadius: 999,
    border: "1px solid",
    fontSize: 11,
    fontWeight: 750,
    lineHeight: 1,
    whiteSpace: "nowrap",
  },
  commitBox: {
    marginTop: 12,
    paddingTop: 12,
    borderTop: "1px solid rgba(20,20,30,0.08)",
  },
  reviewNotice: {
    padding: "8px 10px",
    borderRadius: 8,
    background: "var(--wjn-review-soft)",
    border: "1px solid rgba(198, 138, 26, 0.16)",
    color: "var(--wjn-review)",
    fontSize: 12,
    lineHeight: 1.45,
    marginBottom: 10,
  },
  inlineGhostButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    height: 30,
    padding: "0 9px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.1)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  prismBox: {
    marginTop: 12,
    padding: 10,
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface-subtle)",
  },
  countBadge: {
    minWidth: 24,
    height: 22,
    padding: "0 8px",
    borderRadius: 8,
    background: "rgba(20,20,30,0.06)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    fontWeight: 750,
    lineHeight: "22px",
    textAlign: "center",
  },
  editorPanel: {
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    padding: 14,
  },
  fieldLabel: {
    display: "grid",
    gap: 6,
    marginTop: 10,
    fontSize: 12,
    fontWeight: 700,
    color: "var(--wjn-text-secondary)",
  },
  textInput: {
    width: "100%",
    height: 36,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.1)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text)",
    fontSize: 13,
    outline: "none",
  },
  textArea: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.1)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text)",
    fontSize: 13,
    lineHeight: 1.5,
    resize: "vertical",
    outline: "none",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: 36,
    padding: "0 13px",
    borderRadius: 8,
    border: "1px solid var(--wjn-blue)",
    background: "var(--wjn-blue)",
    color: "#fff",
    fontSize: 12.5,
    fontWeight: 750,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 34,
    padding: "0 11px",
    borderRadius: 8,
    border: "1px solid var(--wjn-accent-line)",
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-blue)",
    fontSize: 12.5,
    fontWeight: 750,
    cursor: "pointer",
  },
  ghostButton: {
    height: 30,
    padding: "0 9px",
    borderRadius: 8,
    border: "1px solid rgba(20,20,30,0.08)",
    background: "var(--wjn-surface)",
    color: "var(--wjn-text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  },
  commitError: {
    marginTop: 10,
    padding: "8px 10px",
    borderRadius: 8,
    background: "rgba(220, 38, 38, 0.06)",
    border: "1px solid rgba(220, 38, 38, 0.12)",
    color: "var(--wjn-error)",
    fontSize: 12,
  },
  commitWarning: {
    marginTop: 10,
    padding: "8px 10px",
    borderRadius: 8,
    background: "rgba(245, 158, 11, 0.08)",
    border: "1px solid rgba(245, 158, 11, 0.16)",
    color: "#92400E",
    fontSize: 12,
  },
  linkWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  roomLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 9px",
    borderRadius: 8,
    background: "var(--wjn-accent-soft)",
    color: "var(--wjn-blue)",
    fontSize: 11.5,
    fontWeight: 650,
    textDecoration: "none",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: 150,
    textAlign: "center",
    borderRadius: 8,
    border: "1px dashed rgba(20,20,30,0.12)",
    background: "var(--wjn-surface-subtle)",
  },
  emptyTitle: {
    fontSize: 13.5,
    fontWeight: 750,
    color: "var(--wjn-text-secondary)",
  },
  emptyDetail: {
    maxWidth: 420,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--wjn-text-muted)",
  },
};
