export const featureSlugToSkillId: Record<string, string> = {
  "deep-research": "deep-research",
  "literature": "literature-management",
  "opening-research": "opening-research",
  "thesis-writing": "fullpaper-writer",
  "figure-generation": "figure-generation",
  "compile-export": "compile-export",
  "literature-search": "deep-research",
  "paper-analysis": "paper-analysis",
  "writing": "writing",
  "literature-review": "literature-review",
  "framework-outline": "framework-designer",
  "peer-review": "peer-reviewer",
  "journal-recommend": "journal-recommender",
  "proposal-outline": "proposal-writer",
  "background-research": "background-research",
  "experiment-design": "experiment-designer",
  "copyright-materials": "copyright-materials",
  "technical-description": "technical-description",
  "patent-outline": "patent-outline",
  "prior-art-search": "prior-art-search",
};
